name: Tests for pull requests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches:
      - "**" # matches every branch
      - "!master" # but excludes master

jobs:
  visual-regression:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm -v
          npm install

      - name: Build Storybook
        run: npm run storybook:build

      - name: Run Loki
        run: npm run loki:ci

      - uses: actions/upload-artifact@v3
        with:
          name: Handle Loki artifacts
          path: .loki/
