name: Tests for pull requests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches:
      - "**" # matches every branch
      - "!master" # but excludes master

jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Build for Lighthouse & serve locally
        run: PUBLIC_URL=/ yarn build && (yarn serve&)

      - name: Run Lighthouse
        uses: foo-software/lighthouse-check-action@master
        id: lighthouseCheck
        with:
          urls: "http://127.0.0.1:3000"
          emulatedFormFactor: "desktop"
      - name: Handle Lighthouse Check results
        uses: foo-software/lighthouse-check-status-action@master
        with:
          lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
          minAccessibilityScore: "90"
          minBestPracticesScore: "90"
          minPerformanceScore: "90"
          minSeoScore: "90"
