name: Tests for pull requests

on:
  pull_request:
    branches:
      - '**' # every branch

jobs:
  visual-regression:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm -v
          npm install

      - name: Build Storybook
        run: npm run storybook:build

      - name: Run Loki
        run: npm run loki:ci

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          include-hidden-files: true
          name: Handle Loki artifacts
          path: .loki/
